### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ao216** [yuxumin/PoinTr#80]
你好！我的研究方向是树木重建，想要引用您的方法来进行点云补齐。我按照您的前三个步骤配置了环境和网络，但是无法进行数据的训练，报错为cuda内存不足。我没有修改过代码，请问您看得出来这是什么原因吗？谢谢！
我是用的是linux云服务器，有40537MiB 的 内存，CUDA版本为11.0
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 39.59 GiB total capacity; 98.78 MiB already allocated; 3.19 MiB free; 116.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
我输入的命令是：
bash ./scripts/test.sh 0 \
    --ckpts ./pretrained/PoinTr_ShapeNet55.pth \
    --config ./cfgs/ShapeNet55_models/PoinTr.yaml \
    --mode easy \
    --exp_name example
附更多运行数据：
2022-11-09 09:58:59,414 - PoinTr - INFO - config.dataset.test.others = edict()
2022-11-09 09:58:59,414 - PoinTr - INFO - config.dataset.test.others.subset : test
2022-11-09 09:58:59,414 - PoinTr - INFO - config.model = edict()
2022-11-09 09:58:59,414 - PoinTr - INFO - config.model.NAME : PoinTr
2022-11-09 09:58:59,414 - PoinTr - INFO - config.model.num_pred : 6144
2022-11-09 09:58:59,414 - PoinTr - INFO - config.model.num_query : 96
2022-11-09 09:58:59,414 - PoinTr - INFO - config.model.knn_layer : 1
2022-11-09 09:58:59,414 - PoinTr - INFO - config.model.trans_dim : 384
2022-11-09 09:58:59,414 - PoinTr - INFO - config.total_bs : 96
2022-11-09 09:58:59,414 - PoinTr - INFO - config.step_per_update : 1
2022-11-09 09:58:59,414 - PoinTr - INFO - config.max_epoch : 200
2022-11-09 09:58:59,414 - PoinTr - INFO - config.consider_metric : CDL2
2022-11-09 09:58:59,414 - PoinTr - INFO - Distributed training: False
2022-11-09 09:58:59,414 - PoinTr - INFO - Set random seed to 0, deterministic: False
2022-11-09 09:58:59,414 - PoinTr - INFO - Tester start ... 
[DATASET] Open file data/ShapeNet55-34/ShapeNet-55/test.txt
[DATASET] 10518 instances were loaded
2022-11-09 09:58:59,426 - MODEL - INFO -  Transformer with knn_layer 1
2022-11-09 09:59:00,785 - PoinTr - INFO - Loading weights from ./pretrained/PoinTr_ShapeNet55.pth...
2022-11-09 09:59:01,006 - PoinTr - INFO - ckpts @ 104 epoch( performance = No Metrics)
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 62, in main
    test_net(args, config)
  File "/home/testNet/PoinTr-master/tools/runner.py", line 294, in test_net
    base_model.to(args.local_rank)
  File "/home/software/anconda/envs/env_open3d_09/lib/python3.7/site-packages/torch/nn/modules/module.py", line 987, in to
    return self._apply(convert)
  File "/home/software/anconda/envs/env_open3d_09/lib/python3.7/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/software/anconda/envs/env_open3d_09/lib/python3.7/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/home/software/anconda/envs/env_open3d_09/lib/python3.7/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/software/anconda/envs/env_open3d_09/lib/python3.7/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/home/software/anconda/envs/env_open3d_09/lib/python3.7/site-packages/torch/nn/modules/module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 39.59 GiB total capacity; 98.78 MiB already allocated; 3.19 MiB free; 116.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by yuxumin** [comment]
这个是因为你卡不够大吧？你可以把config里面的batch size减小一些

**Comment by ao216** [comment]
你好，问题已解决，谢谢！
配置环境时我可能存在cuda、pytorch、python不匹配的情况，重新开一个云服务器账号后进行环境配置，python=3.7 pytorch=0.7.1 cuda=11.0，代码即可运行。
